rss:
  livedoor:
    top: { name: "主要", url: "http://news.livedoor.com/topics/rss/top.xml" }
    dom: { name: "国内", url: "http://news.livedoor.com/topics/rss/dom.xml" }
    int: { name: "海外", url: "http://news.livedoor.com/topics/rss/int.xml" }
    eco: { name: "IT経済", url: "http://news.livedoor.com/topics/rss/eco.xml" }
    ent: { name: "芸能", url: "http://news.livedoor.com/topics/rss/ent.xml" }
    spo: { name: "スポーツ", url: "http://news.livedoor.com/topics/rss/spo.xml" }
    mov: { name: "映画", url: "http://news.livedoor.com/rss/summary/52.xml" }
    gourmet: { name: "グルメ", url: "http://news.livedoor.com/topics/rss/gourmet.xml" }
    love: { name: "女子", url: "http://news.livedoor.com/topics/rss/love.xml" }
    trend: { name: "トレンド", url: "http://news.livedoor.com/topics/rss/trend.xml" }
    full:
      top: { url: "http://fullrss.net/a/http/news.livedoor.com/topics/rss/top.xml", has_summary: true }
      dom: { url: "http://fullrss.net/a/http/news.livedoor.com/topics/rss/dom.xml", has_summary: true }
#      int:
#      eco:
#      ent:
      spo: { url: "http://www.wmutils.com/fulltextrss/feeds/f2b47365d059b3fe28b773a5bb45ba94.xml", has_summary: false }
#      mov:
#      gourmet:
#      love:
#      trend:
