rss:
  livedoor:
    top: { name: "TOP", url: "http://news.livedoor.com/topics/rss/top.xml" }
    dom: { name: "国内", url: "http://news.livedoor.com/topics/rss/dom.xml" }
    int: { name: "海外", url: "http://news.livedoor.com/topics/rss/int.xml" }
    eco: { name: "IT経済", url: "http://news.livedoor.com/topics/rss/eco.xml" }
    ent: { name: "芸能", url: "http://news.livedoor.com/topics/rss/ent.xml" }
    spo: { name: "スポーツ", url: "http://news.livedoor.com/topics/rss/spo.xml" }
    mov: { name: "映画", url: "http://news.livedoor.com/rss/summary/52.xml" }
    gourmet: { name: "グルメ", url: "http://news.livedoor.com/topics/rss/gourmet.xml" }
    love: { name: "女子", url: "http://news.livedoor.com/topics/rss/love.xml" }
    trend: { name: "トレンド", url: "http://news.livedoor.com/topics/rss/trend.xml" }
  yahoo:
    dom: [ 
           "http://headlines.yahoo.co.jp/rss/zdn_mkt-dom.xml",
           "http://headlines.yahoo.co.jp/rss/jct-dom.xml",
           "http://headlines.yahoo.co.jp/rss/withnews-dom.xml",
           "http://headlines.yahoo.co.jp/rss/wordleaf-dom.xml",
           "http://headlines.yahoo.co.jp/rss/san-dom.xml",
           "http://headlines.yahoo.co.jp/rss/logmi-dom.xml"
           ]
    int: [
           "http://headlines.yahoo.co.jp/rss/san-c_int.xml",
           "http://headlines.yahoo.co.jp/rss/wsj-c_int.xml",
           "http://headlines.yahoo.co.jp/rss/wordleaf-c_int.xml",
           "http://headlines.yahoo.co.jp/rss/withnews-c_int.xml",
           "http://headlines.yahoo.co.jp/rss/cnn-c_int.xml",
           "http://headlines.yahoo.co.jp/rss/scn-c_int.xml"
          ]
    eco: [
          "http://headlines.yahoo.co.jp/rss/san-bus.xml",
          "http://headlines.yahoo.co.jp/rss/wordleaf-bus.xml",
          "http://headlines.yahoo.co.jp/rss/logmi-bus.xml",
          "http://headlines.yahoo.co.jp/rss/withnews-bus.xml",
          "http://headlines.yahoo.co.jp/rss/asahik-bus.xml"
          ]
    ent: [
          "http://headlines.yahoo.co.jp/rss/wordleaf-c_ent.xml",
          "http://headlines.yahoo.co.jp/rss/natalieo-c_ent.xml",
          "http://headlines.yahoo.co.jp/rss/san-c_ent.xml",
          "http://headlines.yahoo.co.jp/rss/ykf-c_ent.xml",
          "http://headlines.yahoo.co.jp/rss/nkgendai-c_ent.xml"
          ]
    spo: [  "http://headlines.yahoo.co.jp/rss/wordleaf-c_spo.xml",
            "http://headlines.yahoo.co.jp/rss/ballball-c_spo.xml",
            "http://headlines.yahoo.co.jp/rss/spnannex-c_spo.xml",
            "http://headlines.yahoo.co.jp/rss/nkgendai-c_spo.xml",
            "http://headlines.yahoo.co.jp/rss/scn-c_spo.xml",
            "http://headlines.yahoo.co.jp/rss/san-c_spo.xml",
            "http://headlines.yahoo.co.jp/rss/ykf-c_spo.xml"       ]
    mov: [
            "http://headlines.yahoo.co.jp/rss/nataliee-c_ent.xml",
            "http://headlines.yahoo.co.jp/rss/eiga-c_ent.xml",
            "http://headlines.yahoo.co.jp/rss/mvwalk-c_ent.xml",
            "http://headlines.yahoo.co.jp/rss/flix-c_ent.xml"
          ]
    gourmet: [
             "http://entabe.jp/news/feed.rss",
             "http://mery.jp/gourmet.rss"
            ]
    love: [
             "http://zasshi.news.yahoo.co.jp/rss/jspa-all.xml", 
             "http://mery.jp/fashion.rss"
          ]
    trend: [
             "http://spotlight-media.jp/feed.xml",
             "http://headlines.yahoo.co.jp/rss/nallabout-c_life.xml",
             "http://headlines.yahoo.co.jp/rss/it_nlab-c_life.xml"
          ]

sidebar: ["TOP", "国内", "海外", "IT経済", "芸能", "スポーツ", "映画", "グルメ", "女子", "トレンド"]
