rss:
  livedoor:
    top: { name: "主要", url: "http://news.livedoor.com/topics/rss/top.xml" }
    dom: { name: "国内", url: "http://news.livedoor.com/topics/rss/dom.xml" }
    int: { name: "海外", url: "http://news.livedoor.com/topics/rss/int.xml" }
    eco: { name: "IT経済", url: "http://news.livedoor.com/topics/rss/eco.xml" }
    ent: { name: "芸能", url: "http://news.livedoor.com/topics/rss/ent.xml" }
    spo: { name: "スポーツ", url: "http://news.livedoor.com/topics/rss/spo.xml" }
    mov: { name: "映画", url: "http://news.livedoor.com/rss/summary/52.xml" }
    gourmet: { name: "グルメ", url: "http://news.livedoor.com/topics/rss/gourmet.xml" }
    love: { name: "女子", url: "http://news.livedoor.com/topics/rss/love.xml" }
    trend: { name: "トレンド", url: "http://news.livedoor.com/topics/rss/trend.xml" }
  similar_articles:
    allabout:
      full:
        spo: { url: "http://fullrss.net/a/http/headlines.yahoo.co.jp/rss/nallabout-c_spo.xml", has_summary: false }
    spnavi:
      full:
        spo: { url: "http://fullrss.net/a/http/headlines.yahoo.co.jp/rss/spnavi-c_spo.xml", has_summary: false }
    sankei_spo:
      full: 
        spo: { url: "http://fullrss.net/a/http/headlines.yahoo.co.jp/rss/san-c_spo.xml", has_summary: false }
